#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ClienteAndroid.Resource", IsApplication=true)]

namespace ClienteAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000d
			public const int btnAbajo = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int btnAlerta = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int btnArriba = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int btnBanoAbajoExt = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int btnBanoAbajoInt = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int btnBanoArribaExt = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int btnBanoArribaInt = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int btnBar = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int btnCocina = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int btnGimnasio = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int btnJuegos = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int btnOscar = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int btnPatio = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int btnTaller = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int btnVentilador = 2130968587;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Abajo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Arriba = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int abj_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int arr_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
